### ISSUE TITLE
Some problem with essentials homes

### ISSUE THREAD

**Issue by santocraft** [jerzean/ProtectionStones-Minecraf#1]
For some reason, this is from the owner view, I can not check players homes that have not entered the server yet after installing the plugin. The command /home (Player):home says that the user doesn't have an existing home, until they get online for the first time after the plugin has been installed. If the plugin is removed the command works again perfectly again. Should check it out as it should not create any conflict.
Once again thank you for trying to keep this simple but useful plugin alive. You should post it on spigot and bukkit officially.

Also Can't do /ps info as owner in other people's protections.

**Comment by jerzean** [comment]
@santocraft what plugin are you using for homes? and is the any errors in console( aka stack trace) whhat version of worldguard/worldedit and what version of the /homes plugin are you using

**Comment by santocraft** [comment]
As said above, I'm using essentials, the version that can be found on jenkins for 1.12.2. There's no console errors. and I'm using the latest possible versions of World Guard and World Edit from Bukkit.
