### ISSUE TITLE
Doors

### ISSUE THREAD

**Issue by tads421** [jerzean/ProtectionStones-Minecraf#2]
region Owners are unable to use the doors, this should be true if you are NOT a owner of a region but owners should be able to use the doors.

Chest, Furness are both fine to use just the doors, buttons levers gates etc... Please fix this :)

**Comment by tads421** [comment]
Removing - use deny does the job but i thought that was to deny others to use stuff

**Comment by jerzean** [comment]
thats a worldguard issue    
the "use" flag controls the redstone/doors      
protectionstones   creates a region in worldguard with the player name and stone location as the region name
you can stand in a ps area and type /rg info  and get the exact same info as /ps info, /ps view
all of the flags come from worldguard
